export const TYPES = {
  READ_ALL_DATA: "READ_ALL_DATA",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_TO_CART: "REMOVE_TO_CART",
  CLEAR_CART: "CLEAR_CART",
  DECREASE_CART: "DECREASE_CART",
  ADD_AMOUNT: "ADD_AMOUNT",
};
